# Generated by Django 3.0.4 on 2020-03-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='kind',
        ),
        migrations.AddField(
            model_name='permission',
            name='codename',
            field=models.CharField(default='view_ticket', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default='Can view ticket', max_length=50),
            preserve_default=False,
        ),
    ]
