# Generated by Django 3.0.4 on 2020-03-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200309_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='role_id',
            new_name='role',
        ),
    ]
