# Generated by Django 3.0.4 on 2020-03-10 14:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20200310_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('EN', 'enhancement'), ('BF', 'bugfix'), ('DV', 'development'), ('QA', 'quality assurance')], default='EN', max_length=2)),
                ('complexity', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(5)])),
                ('estimated', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='account.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='account.User')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
    ]
